%YAML 1.2
---

# Field for current dataset, that must be used in code
current:
  
  # Image/video source (video | camera | dataset) 
  source: "dataset"

  # Dataset name from the DATASETS list
  dataset: "kitti"
  
  # Sequence number/name for
  sequence: "00"



# preprocessing:
#   kitti:
#   tum_rgbd:
#   euroc_mav:


datasets:
  kitti:
    resolution: [1271, 376]
    fps: 10

  euroc_mav:
    resolution: [752, 480]
    fps: 20

