%YAML 1.2
---

# Field for current dataset, that must be used in code
current:
  
  # Image/video source (video | camera | dataset) 
  source: "camera"

  # Dataset name from the DATASETS list
  dataset: "kitti"


datasets:
  kitti:
    resolution: [1271, 376]
    seq: "00"
    fps: 10

  euroc_mav:
    resolution: [752, 480]
    seq: "00"
    fps: 20

