%YAML 1.2
---


current:
  # Dataset name from the DATASETS list
  dataset: "kitti"
  sequence: "00"



# preprocessing:
#   kitti:
#   tum_rgbd:
#   euroc_mav:



datasets:
  kitti:
    resolution: [1271, 376]
    fps: 10

  euroc_mav:
    resolution: [752, 480]
    fps: 20