//
// Created by apin on 29.12.2024.
//

#ifndef VINS_FOCUS_INERTIALSOURCEFACTORY_HPP
#define VINS_FOCUS_INERTIALSOURCEFACTORY_HPP


class InertialSourceFactory {

};


#endif //VINS_FOCUS_INERTIALSOURCEFACTORY_HPP
